#!/usr/bin/env bash
# transfer a file using scp
[[ $# -lt 3 ]] && echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY" && exit;

scp -o "StrictHostKeyChecking off" ${4:+-i "$4"} "$1" "$3"@"$2":~/ 
