#!/usr/bin/env bash
# add a redirection
rule="\trewrite ^/redirect_me/?$ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;\n\n"
sed -i "s|\(^\tlocation / {\)|$rule\1|" /etc/nginx/sites-enabled/default
service nginx reload
