#!/usr/bin/env bash
#read

IFS=':'
while read -r user pass uid gid info home shell; do
    printf "The user %s is part of the %s gang, lives in %s and rides %s.  %s's place is protected by the passcode %s, more info about the user here: %s\n" "$user" "$gid" "$home" "$shell" "$uid" "$pass" "$info"
done < /etc/passwd
