#!/usr/bin/env bash
#run nginx as user nginx
read -ra PIDs < <(pidof apache2)
kill "${PIDs[@]}"
chown -R nginx:nginx /etc/nginx
chown -R nginx:nginx /var/log/nginx
chmod 640 /etc/nginx/nginx.conf
sed -i -E '/^\s*listen/s/80/8080/' /etc/nginx/sites-enabled/default
sudo -u nginx -- nginx
